name: Build

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [11, 17, 18, 19]
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}
          cache: gradle
      - run: |
          ./gradlew spotlessCheck build publishToMavenLocal --no-daemon

  reference-checker-tests:
    name: Run Reference Checker Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          path: jspecify
      - name: Check out the reference checker
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/nullness-checker-for-checker-framework
          path: nullness-checker-for-checker-framework
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run Conformance Tests
        id: conformance-tests
        if: github.base_ref == 'main' || github.ref_name == 'main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: conformanceTest conformanceTestOnSamples
          build-root-directory: nullness-checker-for-checker-framework
        continue-on-error: true
      - name: Update conformance test reports
        if: github.event_name == 'push' && github.ref_name == 'main' && steps.conformance-tests.outcome == 'failure'
        run: |
          curl -L \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            "https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/reference-checker/actions/workflows/update-conformance-test-reports.yml/dispatches" \
            -d '{"ref":"main"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Samples Tests
        if: github.base_ref == 'samples-google-prototype' || github.ref_name == 'samples-google-prototype'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jspecifySamplesTest
          build-root-directory: nullness-checker-for-checker-framework
